# Generated by Django 4.2 on 2023-04-15 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0002_comic_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='fron_page',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
